[object Promise]

name: Updates CI
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  release:
    name: Deploy updates
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - name: Update code
        uses: upptime/updates@master
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
